# Generated by Django 4.0.2 on 2022-02-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('release', models.CharField(max_length=150)),
                ('seasons', models.IntegerField()),
                ('episodes', models.IntegerField()),
                ('studio', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=150)),
            ],
        ),
    ]
