# Generated by Django 4.0.2 on 2022-02-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
