# Generated by Django 4.0.2 on 2022-02-26 23:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_anime_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studio',
        ),
        migrations.AlterField(
            model_name='anime',
            name='director',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=main_app.models.get_director_default, size=None),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=main_app.models.get_genre_default, size=None),
        ),
        migrations.AlterField(
            model_name='anime',
            name='img',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.CharField(max_length=350)),
                ('animes', models.ManyToManyField(to='main_app.Anime')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=250)),
                ('air_date', models.DateTimeField()),
                ('eng_air_date', models.DateTimeField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.anime')),
            ],
        ),
    ]
