# Generated by Django 4.0.2 on 2022-02-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_anime_episodes_remove_anime_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default='0'),
        ),
    ]
