# Generated by Django 4.0.2 on 2022-02-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_studios_remove_anime_img_alter_voiceactor_animes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studios',
            options={'ordering': ['pk']},
        ),
    ]
