# Generated by Django 4.0.2 on 2022-02-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_episode_air_date_alter_episode_eng_air_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateField(verbose_name='Original Air Date'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='eng_air_date',
            field=models.DateField(verbose_name='English Air Date'),
        ),
    ]
