# Generated by Django 4.0.2 on 2022-02-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_episode_air_date_alter_episode_eng_air_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='studios',
            options={},
        ),
        migrations.RemoveField(
            model_name='studios',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='voiceactor',
            name='animes',
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ManyToManyField(to='main_app.Studios'),
        ),
    ]
