# Generated by Django 4.0.2 on 2022-02-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_anime_options_alter_studios_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='voice_actors',
            field=models.ManyToManyField(to='main_app.VoiceActor'),
        ),
    ]
